name: main
on: [push, pull_request]
#on:
#  push:
#    branches-ignore:
#      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.8"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@master
      with:
        python-version: 3.8
    - uses: Gr1N/setup-poetry@v7
    - name: Install Dependencies
      run: poetry install
    - name: Run Linter
      run: poetry run flake8 .
    - name: Run Tests
      run: poetry run pytest --cov=./ --cov-report=xml tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
